spring:
  profiles:
    active: local
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 256MB

server:
  port: 2024
  max-http-request-header-size: 64KB
  tomcat:
    # refer to ServerProperties
    max-http-response-header-size: 64KB

    # allow special chars
    relaxedQueryChars: <,>,[,\,\,],^,`,{,|,}

    # allow illegal headers
    rejectIllegalHeader: false

    # enable transparent proxy
    remote-ip:
      remote-ip-header: x-forwarded-for
      protocol-header: x-forwarded-proto

explorer:
  # the headers passed by reverse proxy
  proxy-headers: Host,X-Real-IP,X-Forwarded-For,X-Forwarded-Proto

  # the headers should not be sent to client
  excluded-headers: X-Frame-Options,Content-Security-Policy,Content-Security-Policy-Report-Only,Transfer-Encoding

  host-mappings:
    google: www.google.com
    baidu: www.baidu.com

  block-rules:
    - host-pattern: www\.google\.com
      block-paths: ["/gen_204"]

    - host-pattern: .*\.?baidu\.com
      block-paths: [".*\\.gif", "/ztbox"]
      block-contents:
        - selector: "head"
          append: |
            <style>
            div:has(> .c-abstract) {display:none;}
            .newsTitleTop {display: none;}
            </style>"