# production config
explorer:
  # change this if the host differs from wildcard host
  explorer-url: <your-domain.com>
  # change this if it differs from the host in explorer url
  wildcard-host: <your-domain.com>