# production config
explorer:
  # change this if the host differs from wildcard host
  host: <your-domain.com>
  url: https://<your-domain.com>
  # change this if it differs from the host in explorer url
  wildcard-host: <wildcard-domain.com>