name: Build Explorer

on:
  push:
    branches: [ main ]
    paths:
      - 'build.gradle'
      - 'src/**'
      - '.github/workflows/workflow.yaml'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # https://github.com/marketplace/actions/github-action-for-graalvm
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17' # for the latest JDK 17
          distribution: 'graalvm-community' # New 'distribution' option
          github-token: ${{ secrets.GITHUB_TOKEN }}
#          native-image-job-reports: 'true'
#          components: 'native-image'
          cache: 'gradle'

      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image with Gradle
        run: |
          # gradle bootBuildImage
          # docker tag explorer chuntungho/explorer
          gradle bootJar
          # docker build -t chuntungho/explorer .
          docker buildx build --platform linux/amd64,linux/arm64 --push -t chuntungho/explorer .
 
  deploy:
    runs-on: ubuntu-latest
    needs:
      - build

    steps:
      - name: Deploy in remote server
        uses: appleboy/ssh-action@v1.0.2
        with:
          host: ${{ vars.SERVER_HOST }}
          port: ${{ vars.SERVER_PORT }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          script_stop: true
          script: |
            kubectl rollout restart deployment explorer
